name: "Setup Android Environment"
description: "Setup Android SDK, JDK, fastlane, ruby, and gradle cache, etc"
runs:
  using: "composite"
  steps:
    # Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: 11
    # Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    # Setting up ruby on the machine
    - name: Set up Ruby
      id: set_up_ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true
    # Installing firebase on the machine
    - name: Install firebase tool
      id: install_firebase_tool
      shell: bash
      run: |
        yarn global add firebase-tools
        echo "::add-path::$(yarn global bin)"
    # Gem caching
    - name: Gem caching
      id: gem_cache
      uses: actions/cache@v2
      continue-on-error: true
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    # Installing bundler to use fastlane on the machine
    - name: Setup fastlane
      id: set_up_fastlane
      shell: bash
      run: |
        gem install bundler:1.17.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    # Gradle cache
    - name: Cache Gradle packages
      id: cache_gradle_packages
      uses: actions/cache@v2
      continue-on-error: true
      with:
        path: |
          ~/.gradle/caches/modules-*
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/build-cache-*
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
